grantnav/frontend/static/css/main.css, grantnav/frontend/templates/base.html, grantnav/frontend/templates/terms.html, grantnav/frontend/tests_functional.py, grantnav/frontend/urls.py
This also covers the privacy policy
Note that I have written the page to cover two organisations
I have used the privacy policy from http://www.threesixtygiving.org/privacy/
and pasted that in.
The main text comes from the CoVE terms and conditions page, but with
some re-writes and some sections removed.
A link to this page is placed in the footer with some CSS to theme it
A test is added to check that this page exists and has a h1
=> [#61] [#174] Adds a terms and conditions page

LICENCE.rst, grantnav/frontend/templates/base.html, grantnav/frontend/tests_functional.py
We need to do this under the terms of the licence of the data
Adds info to the licence document and also to the footer.
Adds a test to see that it is displayed on the home page
=> [#99] Adds licence information about code-point data

grantnav/frontend/static/css/main.css, grantnav/frontend/templates/base.html, grantnav/frontend/templates/take_down_policy.html, grantnav/frontend/tests_functional.py, grantnav/frontend/urls.py
The 360Giving site now has a take down policy.
This adds a page that basically tells people to go there for the info
Adds a link in the footer similar to that on the 360Giving site
Also fixes up the css in those footer links to remove a list-style-type which is visible otherwise
Adds tests for those links in the footer
=> Adds a take down policy page

grantnav/frontend/static/css/main.css, grantnav/frontend/templates/base.html
Uses CSS to change the icons used in the data tables on e.g. a funders page
Re-orders where 'extra-style' is loaded in the base template so that our
main.css file gets loaded last. This may have unintended consequences, please review.
=> [#216] Replace green/red icons with up down arrows in data tables

.travis.yml, grantnav/frontend/templates/district.html, grantnav/frontend/templates/funder.html, grantnav/frontend/templates/funders.html, grantnav/frontend/templates/recipient.html, grantnav/frontend/templates/recipients.html, grantnav/frontend/templates/region.html
CSV now comes first on a rendered css view - but not int the code
because of the pull-right css class
NB - not changed on search.html to avoid conflicts
=> [#236] Swaps the order of the JSON and CSV download buttons

grantnav/frontend/templates/about.html, grantnav/frontend/templates/base.html, grantnav/frontend/templates/help.html, grantnav/frontend/tests.py, grantnav/frontend/tests_functional.py, grantnav/frontend/urls.py
- Create a "Help with Using GrantNav" page with text as agreed with 360
- Combine the current "Advanced Search" page into this page
- Add a table of contents with internal page links
- Make the formatting of the Advanced Search part clearer, and make examples (a bit) more relevant
- Remove the now-redundant separate Advanced Search page
- Link from footer to new "Help with Using GrantNav" page (and delete the advanced search link)
- Fix tests to match
=> New Page: Help with Using GrantNav

LICENCE.rst, dataload/WD15_LGD15_NI_LU.csv, dataload/import_to_elasticsearch.py, grantnav/csv_layout.py, grantnav/frontend/templates/datasets.html, grantnav/frontend/tests_functional.py
At the moment, because GN relies on Code Point open for both postcode and ward/district/area lookups, NI geocodes and names are missing. I've added the relevant NI lookup csv, and modified the data import to add these codes and names, meaning any grant data with an geocode in NI will have the additional fields added.
Also, if  a postcode starts with 'BT' we can safely assume this is in Northern Ireland (a simple fact, there's no licensing issues in this case).
=> NI geographies - lookups & postcode

grantnav/frontend/templates/help.html
Small typo I made in the spelling of "fundingOrgani**z**ation" which meant that this example is incorrect
=> Fix a typo in help page example

grantnav/frontend/templates/base.html
The zero is missing from the front of the number. Is this an in-joke?
Also, I added links to the respective pages on Co House and Charity Commission
=> the 360Giving Company Number in the footer is wrong

grantnav/frontend/static/css/main.css, grantnav/frontend/templates/search.html, grantnav/frontend/tests.py, grantnav/frontend/tests_functional.py, grantnav/frontend/views.py
Problem:
When a user searches for 'music therapy' (without quotes), the results can include 'music' or 'therapy'.
When a user searches for 'music therapy' (with quotes), the results include both words.
User could use 'and' or 'or' without knowing the impact in the search.
Solution:
Display information messages in those cases. The messages are a proposal, you can make better recommendations.
Without quotes:
'If you use quotes around your search, the result will be more accurate.'
And:
'"And" requires each word to be found'
Or:
'"Or" requires one of the two words to be found'
=> 15540-37 'and' vs 'or' queries [WIP - do not merge]

grantnav/frontend/static/css/main.css, grantnav/frontend/tests_functional.py, grantnav/frontend/views.py
Changed 'Advanced Search' box UI and 'or' example.
=> 15540 37 and vs or queries nicer box

dataload/import_to_elasticsearch.py, grantnav/frontend/static/css/main.css, grantnav/frontend/static/css/theme.css, grantnav/frontend/templates/help.html, grantnav/frontend/templates/home.html, grantnav/frontend/templates/search.html, grantnav/frontend/templatetags/frontend.py, grantnav/frontend/tests.py, grantnav/frontend/tests_functional.py
Relates to #479 
Add extra search option by 'Only titles and descriptions'
=> 479 search titles and desc

grantnav/frontend/templates/grant.html, grantnav/frontend/templates/search.html, grantnav/frontend/tests_functional.py
@morchickit last GN PR! This adds the info link to £0 grants from #410 . Are you happy for us to merge this and get it live? The (i) links to the £0 part of the help page
=> Add help link for £0 grants

dataload/import_to_elasticsearch.py
See #503 
This is a massive hack. But I did it on live to get the most recent GN load working. Alternative ideas (other than telling publishers not to do that, or re-ordering the registry!) welcome.
=> Add Reference field to elastic schema

.travis.yml, README.md, grantnav/frontend/tests_functional.py, grantnav/settings.py, requirements.in, requirements.txt, requirements_dev.in, requirements_dev.txt
- Update Travis to use correct disto
- Update Travis to use correct python3 version
- Update README for correct java version for xenial
- Update chromedriver to use latest stable
- Update Django to latest version with security fix #522
- Fix Djanog settings to use MIDDLEWARE instead of deprecated
MIDDLEWARE_CLASSES (pytest-django errors on this)
- Fix floating versions in requirements*.in
- Fix test that checks urls http -> https
- Fix openpyxl version related issue #526
- Remove coveralls Not used and not compatible version with pytest-cov
=> travis Update Travis distro and fix all issues caused by this

grantnav/frontend/views.py
This replaced the "_all" for "*" in the json query in order that the
query becomes compatible with ES7 version of GrantNav.
Fixes https://github.com/ThreeSixtyGiving/grantnav/issues/541
=> views: Add redirect to fix old saved search URLS

dataload/import_to_elasticsearch.py
As we don't restrict what fields are added to publisher's data use our mappings as the definitive list and ignore all other fields unless explicitly added to
the mapping.
https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/529
=> dataload: import_to_elasticsearch: Remove dynamic mapping

grantnav/provenance.py
Make sure that GrantNav can still run if the provenance file specified
disappears. This can happen if the source data breaks for some reason
(e.g. download failed/interrupted or datastore error)
Fixes https://github.com/ThreeSixtyGiving/grantnav/issues/552
=> provenance: Make FileNotFoundError non-fatal to application

grantnav/frontend/templates/help.html
Fixes issue  https://github.com/ThreeSixtyGiving/grantnav/issues/528
=> templates: help: Remove broken link to stats page

dataload/import_to_elasticsearch.py
This helps us to abort any further process as this will generate the
correct exit status and cause the shell script that this is usually
triggered from to abort too.
https://github.com/ThreeSixtyGiving/grantnav/issues/562
=> dataload: import_to_elasticsearch: If error from ES raise an exception

dataload/import_to_elasticsearch.py
Add some comments on our special GrantNav specific fields.
I was going to refactor these fields into their own object but frankly after trying with one field it is a lot of work for little gain. Add some documentation so that the field mappings are clearer.
=> import_to_elasticsearch: Add comments on internal fields

grantnav/frontend/templates/base.html
We're not using cookie based analytics so disable this client side.
=> frontend: templates: base: add disableCookies to Matomo config

grantnav/frontend/templates/grant.html, grantnav/frontend/tests_functional.py
Fixes https://github.com/ThreeSixtyGiving/grantnav/issues/668
=> templates: grant: Update link to the zero value help text

grantnav/frontend/urls.py
When this is hit due to an old link this is currently causing a 500
error due to the template being missing. Redirect the help to
https://help.grantnav.threesixtygiving.org/
=> frontend: urls: Remove redundant /help route and redirect to new help

grantnav/frontend/templates/components/grant-search-result.html
We should be showing a date for each grant in the results.
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/673
=> templates: components: grantnav-search-result: Add award date

.github/ISSUE_TEMPLATE/developer.md
Add a reminder for developers on what information should be included.
=> github: issue templates: Add developer issue

dataload/import_to_elasticsearch.py
If the server is effectively "busy" due to it not currently having
enough memory available we can wait for the GC to happen by adding
retry and backoff - both of which a disabled unless specified.
https://github.com/ThreeSixtyGiving/grantnav/issues/746
=> import_to_elasticsearch: Add retry if unable to load data

grantnav/settings.py
Capture this exception to avoid creating so many error reports on
sentry in production.
fixes https://github.com/ThreeSixtyGiving/grantnav/issues/678
=> settings: Add handler for DisallowedHost exception

.gitmodules
This is required for the Read the Docs build to succeed.
=> gitmodules: Change the 360-ds submodule to use https not ssh

dataload/import_to_elasticsearch.py
https://github.com/ThreeSixtyGiving/insights-ng/issues/16
This is so I can make a link like https://grantnav.threesixtygiving.org/search?query=+additional_data.recipientDistrictGeoCode%3AE07000008+additional_data.recipientDistrictGeoCode%3AE07000009 from Insights to GrantNav, based on the filters Insights has applied.
@kindly Does this look like a resonable thing to do?
=> dataload: Add some extra keyword fields to handle links from Insights

grantnav/frontend/templates/components/search-summary-box.html
I think the way Insights parses url parameters has changed in Insights NG, and they now need to be properly encoded.
=> urlencode query_string before passing it to Insights

docs/_templates/layout.html, fail.html, grantnav/frontend/templates/terms.html
PR in preparation for matomo migration
=> templates: update matomo url to analytics.threesixtygiving.org

grantnav/frontend/templates/components/grants_table_scripts.html, grantnav/frontend/templates/components/results-title.html
+ Remove "Search all fields" search bar in table view
+ Rename "Card view" to "Classic view"
Related issue: https://github.com/ThreeSixtyGiving/grantnav/issues/875
1. Make a search in GrantNav
2. In the results, ensure there are two buttons that read "Classic view" and "Table view"
3. In table view, ensure there is no search field above the table of results
=> frontend: templates: Table view minor changes

grantnav/frontend/static/css/main.css, grantnav/frontend/templates/search.html
#852 
This makes the insights link more responsive, by adding padding so that elements don't overlap and reducing the copy below a certain breakpoint.
We could flex-wrap the elements in the content-filters onto different rows as an alternative.
=> insights: Make the button more responsive

docs/index.md, docs/organisations.md
* Switch to UK spelling of "organizations" so that it picks up the correct .md file
* Make the headings on the organisations page sub headings of the main page to avoid them all appearing in the menu
=> docs: Fix page hierarchy for Organisations

grantnav/frontend/tests.py, grantnav/prometheus/views.py
Now that we have multiple datatypes we need to select grant data as the type of total we're looking for here.
Add test to test for this regression in the future
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/924
=> grantnav: prometheus: Fix grant totals count

grantnav/frontend/static/css/main.css, grantnav/frontend/templates/components/dropdown-filter.html, grantnav/frontend/templates/components/grants_table.html, grantnav/frontend/templates/search_widgets.html
+ Add sort dropdown to widget builder settings.
+ Add "Visualise in 360Insights" button to table view
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/923 & part of https://github.com/ThreeSixtyGiving/grantnav/issues/918
1. Visit the widget builder
2. Make a search query and select a sort order using the "Sort by" dropdown
3. The page should reload with the selected sort applied, and reflected in the preview
4. Copy code and embed elsewhere to verify the sort order is preserved
and
1. Return to home and perform a search, using filters to limit results to < 10,000
2. "Visualise in 360Insights" button should be visible in both classic and table view
=> widgets: add sort dropdown to settings

grantnav/frontend/static/css/main.css, grantnav/frontend/templates/components/grants_table.html, grantnav/frontend/templates/components/grants_table_scripts.html
+ Remove table scrollY
+ Add table pagination
+ Fix broken responsiveness (caused by removing scrollY)
+ Set table height to show 25 results minimum
Relies upon: https://github.com/ThreeSixtyGiving/360-ds/pull/88
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/906
1. Make a search; the results should show the following components:
+ Dropdown list at the top of the table showing length of displayed entries, with "Show 25 entries" by default
+ Pagination at the bottom of the table, styled to imitate Design System pager component
2. The "Description" column should be hidden as a child row at any screen width
3. Make the screen narrower; the columns should collapse into the child row until, at tablet/mobile width, only the "Title" column is visible.
=> tables: manually apply responsivity & pagination

.eslintrc, .gitignore, README.md, grantnav/frontend/templates/components/cookie-consent.html, grantnav/frontend/templates/components/dropdown-filter.html, grantnav/frontend/templates/components/grants_table_scripts.html, grantnav/frontend/templates/components/search-summary-box.html, grantnav/frontend/templates/currency_stats.html, grantnav/frontend/templates/district.html, grantnav/frontend/templates/org.html, grantnav/frontend/templates/region.html, grantnav/frontend/templates/search.html, grantnav/frontend/templates/search_widgets.html, grantnav/frontend/templates/widgets/grantnav_link_script.html, package-lock.json, package.json
+ Add form controls on widget builder to customize widget width
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/873
Also,
+ Add ESLint to statically analyse JS and `<script>` tags within HTML
+ Perform lint operation and fixes (inc. whitespace / indentation, changing syntax to ES6, etc.)
1. Visit Widget Builder
2. In widget settings section, ensure new 'Widget width' form is displayed, including:
+ Numerical `<input>`
+ Dropdown `<select>` with 'pixels' and 'percent' options
3. Ensure making changes to Widget width controls are reflected in the `code` and preview
Optional:
+ (ESLint) Check everything JS-related still works!
=> widgets: add width controls & ESLint (2)

grantnav/frontend/templates/components/grants_table_scripts.html, grantnav/frontend/templates/widgets/tabular_grants.html
When we've embedded a table as a widget we want to make sure clicking links to data takes us to Grantnav in a new window.
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/954
=> templates: table widget: Make sure in widget mode to open in new window

docs/developers.md, docs/export.md, grantnav/frontend/urls.py, grantnav/frontend/views.py
De-duplicate this functionality and remove url and view Update internal docs to reflect change.
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/955
=> grantnav frontend/docs: Remove /api/ downloads in favour search export

grantnav/frontend/templates/widgets/widgets_header.html
+ Update copy
Fixes https://github.com/ThreeSixtyGiving/grantnav/issues/964
1. Open a widget or the widget builder
2. Verify the copy reads, "To explore this dataset in more detail, or filter the search results, open in Grantnav".
=> frontend: widgets: Update CTA copy

grantnav/frontend/templates/components/grants_table_scripts.html, grantnav/frontend/templates/search_widgets.html
+ Add input for restricting results to specific number of rows
+ Show / hide pagination controls based on number of rows
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/959
+ Visit the widgets builder
+ Leave the rows input empty or at 0
+ Verify the page length options still work and number of rows changes accordingly
+ Verify the pagination controls are displayed
+ Change the rows input to > 0
+ Verify the table shows the selected number of rows
+ Verify the pagination controls are hidden
=> frontend: widgets: Allow number of rows to be specified

grantnav/frontend/templates/components/org-page-recipient.html, grantnav/frontend/views.py
As we need to specify a size of results set this to the total number of funders in the system (currently 258).
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/983
=> views: get_recipient_funders Change funders limit to total funders

grantnav/settings.py
This avoids any potential namespace clashes on servers which have other applications running on them as this can be an URL setup in the global webserver name space.
=> settings: Namespace the static directory

grantnav/csv_layout.py
This PR implements feature requested in issue https://github.com/ThreeSixtyGiving/grantnav/issues/928 to add the Funding Type field to GrantNav CSV downloads https://standard.threesixtygiving.org/en/latest/technical/reference/#funding-type
I found the path `fundingType.0.title` with reference to:
* The JSON schema says `fundingType` is an Array of Classification https://standard.threesixtygiving.org/en/latest/_static/docson/index.html#../360-giving-schema.json
* the paths listed in this "360Giving Data Standard Schema" table https://standard.threesixtygiving.org/en/latest/technical/reference/#giving-data-standard-schema
Closes #928
Only thing I'm not sure about, should the CSV field be just `Funding Type` instead of `Funding Type:Title`?
=> Add Funding Type:Title to download

docs/refining_results.md, docs/search_bar.md
This updates the Refining Results page of the helpsite docs with new information as well as refactors some internal links to :doc: and :ref: in appropriate places, to ensure internal linking works in RST.
The resulting page can be viewed [here](https://help.grantnav.threesixtygiving.org/en/mm-helpsite-fixes/refining_results/#).
=> Update Filter reference table and fix internal references

grantnav/frontend/tests_functional.py
Remove temp work around for a fix to help.grantnav site that is now live.
=> tests_functional: Remove temp workaround for helpsite error

grantnav/frontend/templates/grant.html, grantnav/frontend/templates/org.html, grantnav/frontend/views.py
This PR:
* Updates the helptext for the "Where is this data from?" notice on Grant and Org pages.
* Enables autofill of the GrantNav Link field on grantee amendment form when the form is accessed from grantnav.
Only merge once:
=> Passthrough current Grant/Org URL to the Grantee Amendmends form
