- grantnav/frontend/templates/grant.html
- grantnav/frontend/templates/search.html
- grantnav/frontend/urls.py
- grantnav/frontend/views.py
Grant page linked to from the search results, with the same information as the search results.
> [#15] Basic grant page

- dataload/import_to_elasticsearch.py
- grantnav/frontend/static/css/main.css
- grantnav/frontend/templates/base.html
- grantnav/frontend/templates/funder.html
- grantnav/frontend/templates/grant.html
- grantnav/frontend/templates/recipient.html
- grantnav/frontend/templates/search.html
- grantnav/frontend/templatetags/frontend.py
- grantnav/frontend/tests.py
- grantnav/frontend/urls.py
- grantnav/frontend/views.py
Produce pages with basic stats and tables
Add datatables and make api endpoints for it.
> Create Funder and Recipient Page

- grantnav/frontend/templates/funder.html
- grantnav/frontend/templates/recipient.html
- grantnav/frontend/views.py
* Change recipient search to use AND not OR
* Make recipient cardinallity is more accurate for total table rows.
* Fix spelling errors
> [#47] Minor Fixes iteration 2

- grantnav/frontend/views.py
- grantnav/search.py
- grantnav/settings.py
- requirements.in
- requirements.txt
- requirements_dev.in
- requirements_dev.txt
- update_requirements.sh
> [#34] Update requirements, and add shell script to make update easier

- grantnav/frontend/templates/funder.html
- grantnav/frontend/templates/recipient.html
- grantnav/frontend/templates/search.html
- grantnav/frontend/templatetags/frontend.py
- grantnav/frontend/tests_functional.py
Also fixes some date parsing which broke on new version of dateutil.
> [#49] Add comma seperator to counts

- dataload/codelist.csv
- dataload/import_to_elasticsearch.py
- grantnav/frontend/templates/recipient.html
- grantnav/frontend/templates/search.html
- grantnav/frontend/views.py
Use codepoint data to add region/district using postcode and to add
region to lottery data.
> [#63] Add location facet

- dataload/import_to_elasticsearch.py
This prevents search_phase_execution_exception
https://github.com/OpenDataServices/grantnav/issues/74
> [#74] Add a sleep after creating elasticsearch schema

- grantnav/frontend/tests_functional.py
https://github.com/OpenDataServices/grantnav/issues/178
> [#178] Add environment variable to run tests with different browser

- README.md
- grantnav/frontend/templates/base.html
- grantnav/frontend/tests_functional.py
- grantnav/settings.py
- requirements.in
- requirements.txt
- requirements_dev.txt
- update_requirements.sh
I've force unmerged and recreated https://github.com/OpenDataServices/grantnav/pull/176 because I think it has files it shouldn't.
Original comment:
> Uses the django-cookie-law package to do this
> [#62] Adds a cookie acceptance banner to the application

- grantnav/frontend/templates/base.html
- grantnav/frontend/templates/search.html
https://github.com/OpenDataServices/grantnav/issues/21
> [#21] Log site search using piwik javascript function

- grantnav/frontend/templates/base.html
- grantnav/frontend/tests_functional.py
Sets this as 360Giving GrantNav
Provides a test of this
> [#227] Provides a generic title in the title tag

- grantnav/frontend/static/css/main.css
- grantnav/frontend/templates/district.html
- grantnav/frontend/templates/funder.html
- grantnav/frontend/templates/funders.html
- grantnav/frontend/templates/recipient.html
- grantnav/frontend/templates/recipients.html
- grantnav/frontend/templates/region.html
- grantnav/frontend/templates/search.html
Right aligns buttons there were left alligned
Adds some padding to space them out a bit
Adds alt text to the images used as buttons
Changes the id to a class as you can't have the same id used twice
> [#222] Polishes up download buttons

- grantnav/frontend/templates/search.html
- grantnav/frontend/tests_functional.py
Also improves the messages on the no results page and on the
invalid search term page
> [#224] Shows filters on no results page

- LICENCE.rst
Fixes up some .rst links and adds the Charity Commission references
> [#202] Updates the license with info about the Charity Commission data

- grantnav/frontend/static/css/main.css
- grantnav/frontend/templates/district.html
- grantnav/frontend/templates/funder.html
- grantnav/frontend/templates/funders.html
- grantnav/frontend/templates/recipient.html
- grantnav/frontend/templates/recipients.html
- grantnav/frontend/templates/region.html
- grantnav/frontend/tests_functional.py
I think this gets all the tables!
> [#194] Right aligns monetary amounts in tables

- grantnav/frontend/sass/_variables.scss
- grantnav/frontend/static/css/main.css
- grantnav/frontend/static/css/theme.css
Removes the rounded corner css on the navbar
> [#212] Rounded corner nav bug

- README.md
- grantnav/frontend/templates/base.html
- grantnav/frontend/templates/datasets.html
- grantnav/frontend/templates/grant.html
- grantnav/frontend/templates/grants.csv
- grantnav/frontend/templates/publisher.html
- grantnav/frontend/templatetags/frontend.py
- grantnav/frontend/tests_functional.py
- grantnav/frontend/urls.py
- grantnav/frontend/views.py
- grantnav/provenance.py
- grantnav/settings.py
https://github.com/OpenDataServices/grantnav/issues/166
Demo at http://acceptable-license.166-publisher-pages.grantnav-dev.default.opendataservices.uk0.bigv.io/
Also includes substantial copyright related changes to the footer.
> Publisher and "data used in GrantNav" pages

- grantnav/frontend/templates/base.html
- grantnav/frontend/tests.py
This is as per the 360Giving style
> [#110] Changes grant-making to grantmaking

- grantnav/frontend/static/css/main.css
- grantnav/frontend/templates/base.html
- grantnav/frontend/tests_functional.py
Turns into a 3 column footer
Responsive design seems ok to me
Placeholder for git commit in place
> [#55] Changes the footer

- grantnav/frontend/templates/help.html
- grantnav/frontend/tests.py
- grantnav/frontend/urls.py
Just based off some text we've had hanging around in the ticket
No idea if it's any use
Sets it up with basic translation
> [#9] Adds a help/advanced search page

- grantnav/frontend/templates/home.html
- grantnav/frontend/tests.py
Please review. It may not be quite waht is required.
Finding it hard to provide just the right kind of thing here.
> [#213] Provides better exampls on the front page

- dataload/import_to_elasticsearch.py
- requirements.in
- requirements.txt
- requirements_dev.txt
> 284 stream upload

- grantnav/frontend/views.py
This helps spreadsheet programs realise that it's UTF-8.
> [#318] Add UTF-8 bom to CSV output

- grantnav/frontend/templatetags/frontend.py
- grantnav/frontend/tests.py
- grantnav/frontend/tests_functional.py
- grantnav/frontend/views.py
- grantnav/provenance.py
#307 
Also includes tests of this, which means wiring up the tests to load the provenance data.
> [#307] Fix circular ref in JSON output

- grantnav/frontend/templates/base.html
> [#300] Ensure that piwik tracking code is configureable

- grantnav/frontend/templates/base.html
- grantnav/frontend/templates/datasets.html
- grantnav/frontend/templates/take_down_policy.html
- grantnav/frontend/templates/terms.html
- grantnav/frontend/tests.py
- grantnav/frontend/tests_functional.py
> 331 textchanges dc

- grantnav/frontend/templates/about.html
- grantnav/frontend/templates/base.html
- grantnav/frontend/tests_functional.py
- grantnav/frontend/urls.py
This should be all we need to create the long awaited about page.
I do think there is more that could be done here - but the text has been signed off.
There could be:
1) Links to Esmée Fairbairn Foundation, Indigo Trust and Nesta
2) Other link text could be better written - see e.g. https://www.nomensa.com/blog/2011/writing-good-link-text http://www.webcredible.com/blog/writing-effective-link-text/
> About page

- grantnav/frontend/templates/base.html
- grantnav/frontend/templates/datasets.html
- grantnav/frontend/templates/home.html
- grantnav/frontend/templates/take_down_policy.html
- grantnav/frontend/templates/terms.html
- grantnav/frontend/tests_functional.py
> [#340] Text edits

- dataload/import_to_elasticsearch.py
This should fix some dataloding issues.
> [#339] Add extra types to the elasticsearch schema

- requirements.txt
- requirements_dev.txt
https://docs.djangoproject.com/en/1.8/releases/1.8.16/
> Update pinned Django version for security updates

- grantnav/frontend/templates/datasets.html
> Adds content about data updates

- LICENCE.rst
Modelled after the note in https://github.com/OpenDataServices/cove/blob/master/LICENCE.rst
> State that the license doesn't apply to the theme

- README.md
> This application is currently undergoing final testing before a production launch.
is no longer true
> Updates README - takes out line about testing

- grantnav/frontend/views.py
Funder name on funder page came from name of first result on that page.
Now it comes from the filter name of that result making it more
consistant.
> [#409] Funder name now comes from filter name.

- dataload/import_to_elasticsearch.py
> [#374] Remove typo from the elasticsearch mapping

- dataload/import_to_elasticsearch.py
#381 
Dev instance to test: http://current.acceptable-license-valid.381-accents.grantnav-dev.default.threesixtygiving.uk0.bigv.io/
> [#381] Add asciifolding filter to ignore accents

- grantnav/frontend/templates/base.html
> Add meta property="og:title" and property="og:description"

- grantnav/csv_layout.py
> [#435] Map to correct JSON field for "Planned Dates:Duration (months)"

- dataload/codelist.csv
> update to Codepoint vOctober 2017

- dataload/import_to_elasticsearch.py
- grantnav/csv_layout.py
- grantnav/frontend/templatetags/frontend.py
- grantnav/frontend/tests.py
#382 
This PR also gets rid of _(B)_ s in district names as for #345
> Include geo codes in data added by grantnav

- requirements.txt
- requirements_dev.txt
Fails due to https://github.com/OpenDataServices/grantnav/pull/457
> Update Django patch release

- grantnav/frontend/views.py
> [#459] Use correct JSON MIME type

- grantnav/frontend/templates/base.html
- grantnav/frontend/templates/datasets.html
- grantnav/frontend/tests_functional.py
> Delete Copyright and attribution in datasets

- grantnav/frontend/templatetags/frontend.py
> Stop 'title_and_description' key to appear in grants

- requirements.txt
- requirements_dev.txt
Also pins some extra required dependencies.
> Update insecure requirements

- README.md
- grantnav/frontend/templates/datasets.html
Also update this in the README
> templates dataset Update link to correct for Data registry and NI data

- requirements.txt
- requirements_dev.txt
Couple of security updates to Django
see https://github.com/ThreeSixtyGiving/grantnav/pull/537
> requirements: Run update requirements

- grantnav/frontend/templates/funder.html
> change 'search' to 'search recipients' in funder's page

- grantnav/frontend/tests.py
- grantnav/frontend/views.py
> 514 orgid with dots breaks

- grantnav/frontend/templates/datasets.html
- grantnav/frontend/templates/publisher.html
Add spaces between the items in the "Funders covered" cell.
> templates: Datasets tables "Funders covered" add spaces

- grantnav/frontend/static/css/main.css
- grantnav/frontend/templates/search.html
- grantnav/frontend/templatetags/frontend.py
- grantnav/frontend/views.py
> 569 large facet dropdown

- grantnav/frontend/static/css/main.css
- grantnav/frontend/templates/home.html
Closes #549 
Add Covid-19 Banner to home page
> Covid-19 banner

- docs/_templates/_parts/hero.html
- docs/_templates/base.html
> docs: Update logo to the main 360 logo and not standards

- grantnav/frontend/views.py
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/656
> frontend: views: Add URL backwards compatibility for pre-2020 URLS

- docs/_templates/_parts/hero.html
- docs/_templates/_parts/top-bar.html
- docs/export.md
- docs/index.md
> Docs site fixes

- docs/_templates/layout.html
- fail.html
- grantnav/frontend/templates/terms.html
Also update in fail.html. Not sure if this file is active anywhere
though.
> docs/terms: Update Matomo links in docs and terms iframe

- README.md
- grantnav/frontend/sass/box.scss
- grantnav/frontend/sass/global/_reset.scss
- grantnav/frontend/static/css/theme.css
- grantnav/frontend/templates/base.html
- grantnav/frontend/templates/grant.html
> where is this data from links

- docs/_templates/_parts/footer.html
- grantnav/frontend/templates/components/footer.html
> Update GitHub link to point to the grantnav repo

- grantnav/frontend/templates/components/footer.html
> Add build number in footer

- grantnav/frontend/templates/components/footer.html
> Add GH issues link in footer

- grantnav/frontend/views.py
Currently this raises a KeyError if not checked before trying to access
it if someone puts the incorrect publisher_id in the url.
Also remove some random whitespace in the file.
Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/676
> frontend: views: fix the check for publisher_id existing

- grantnav/frontend/templates/datasets.html
related to https://github.com/ThreeSixtyGiving/grantnav/issues/691
> frontend: templates: datasets: showing funders name instead of template var 

- docs/developers.md
> Fixed typo

- grantnav/frontend/templates/components/filters/groups/geography-filters.html
- grantnav/frontend/templates/components/filters/groups/recipient-filters.html
https://github.com/ThreeSixtyGiving/grantnav/issues/624
Also fixes:
https://github.com/ThreeSixtyGiving/grantnav/issues/657
> Facets: Make top level accordians open by default

- dataload/import_to_elasticsearch.py
- grantnav/frontend/views.py
Sends a post request to change max bucket size on the cluster after
a new index is created.
https://github.com/ThreeSixtyGiving/grantnav/issues/685
> Facets: Increace max bucket size.

- grantnav/frontend/sass/custom.scss
- grantnav/frontend/static/css/theme.css
- grantnav/frontend/templates/components/filters/lists/filter-list-year.html
- grantnav/frontend/templates/search.html
- grantnav/frontend/templatetags/frontend.py
- grantnav/frontend/views.py
- grantnav/utils.py
Adds an option for filtering by date range using a datepicker library.
> Filter: Add date range filter.

- grantnav/frontend/templates/base.html
Pre-deploy bump for deploy on 22-06-2021
> frontend: base: Bump the theme date to ensure browser cache clears

- grantnav/frontend/templates/components/filters/lists/filter-list-amount-awarded.html
- grantnav/frontend/templates/components/filters/lists/filter-list-year.html
- grantnav/frontend/views.py
> Facets:  Do not do large aggs on recipients/funders if not needed.

- grantnav/frontend/views.py
Extra query being run each time which was taking
0.5 seconds when querying all the data.
Extra query only needs to run when amount facet selected.
> Search: Speedup results by not doing unnecessary query.

- grantnav/frontend/templatetags/frontend.py
> search-summary: Fix get_year check

- grantnav/frontend/templates/components/search-summary-box.html
- grantnav/frontend/templatetags/graphs.py
> Summary stats years update

- dataload/import_to_elasticsearch.py
fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/664
> import_to_elasticsearch: Add more fields to search index

- grantnav/frontend/templates/funders.html
> Funders total amount only in pounds

- docs/locations.md
relates to https://github.com/ThreeSixtyGiving/grantnav/issues/690
> location only works with UK geography

- dataload/import_to_elasticsearch.py
relates to https://github.com/ThreeSixtyGiving/grantnav/issues/681
> dataload: import_to_elasticsearch: use canonical name.

- grantnav/frontend/templates/components/filter-wrapper.html
- grantnav/frontend/templates/components/filters/groups/funder-filters.html
- grantnav/frontend/templates/components/filters/lists/filter-list-programme-title.html
- grantnav/frontend/templates/search.html
- grantnav/frontend/views.py
change name to 'grant programme title'
move box under funder
> frontend: templates: components: programme title

- grantnav/frontend/static/css/main.css
- grantnav/frontend/templates/search.html
#852
Screenshot: https://github.com/ThreeSixtyGiving/grantnav/issues/852#issuecomment-1277756998
> insights link: Upgrade insights links

- grantnav/frontend/templates/components/grants_table.html
@Lathrisk would this work to fix #915 ?
> frontend: templates: grants_table: Fix missing parameters from download

- README.md
- docs/developer/docker-compose.md
Document how to load funder and recipient data in the appropriate READMEs.
+ Add more detail to main `README.md`
+ Add instructions and examples to `docker-compose.md`
> docs: Document loading funders & recipients data

- grantnav/frontend/templates/components/footer.html
> footer: Update address

- grantnav/frontend/templates/components/cookie-consent.html
+ Add 30-day expiry for cookie
Partially fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/982
> matomo: Set cookie expiry

- dataload/import_to_elasticsearch.py
> import_to_elasticsearch: Change simple_grant_type to "For regrant"

- grantnav/frontend/templates/components/search-summary-box.html
fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/997
> frontend: search-summary-box: Fix incorrect var assignment

- grantnav/frontend/templates/components/org-page-recipient.html
- grantnav/frontend/templates/org.html
- grantnav/frontend/templates/search.html
https://github.com/ThreeSixtyGiving/grantnav/issues/983
> frontend: org-pages: Set generic datatable default to scrollY

- grantnav/frontend/templates/components/grants_table.html
- grantnav/frontend/templates/components/grants_table_scripts.html
- grantnav/frontend/templates/search_widgets.html
Fixes https://github.com/ThreeSixtyGiving/grantnav/issues/996
> frontend: widgets: Allow columns to be selected

- grantnav/frontend/static/css/main.css
This updates the 360-ds to the latest and re-compiles the css file
> css: Update 360-ds

- grantnav/frontend/views.py
Adds new string case matching to add matching against FindThatCharity given names in the data.
Related: https://github.com/ThreeSixtyGiving/grantnav/issues/965
> views: filter_search_ajax Add case matching

- docs/locations.md
Update to reinstate the mention of Ward names/codes working. This can be deployed ASAP (but still need to hold off on deploying grantee amendments copy)
> Update locations: ward.md

- grantnav/frontend/templates/datasets.html
> templates: Update retention days to match changes
